# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: rpm/golang-deepin-go-lib.spec

# add or remove files that should be synced
synced_files:
    - rpm/golang-deepin-go-lib.spec
    - .packit.yaml

upstream_package_name: go-lib
# downstream (Fedora) RPM package name
downstream_package_name: golang-deepin-go-lib

actions:
  fix-spec-file: |
    bash -c "sed -i -r \"0,/Version:/ s/Version:(\s*)\S*/Version:\1${PACKIT_PROJECT_VERSION}/\" rpm/golang-deepin-go-lib.spec"
